name = "asset"
version = "1.1.0"

description = "A tool for converting to Gleam's new `assert` syntax"
licences = ["Apache-2.0"]
repository = { type = "github", user = "GearsDatapacks", repo = "asset" }
links = [
  { title = "Sponsor", href = "https://github.com/sponsors/GearsDatapacks/" },
]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
glance = ">= 5.0.0 and < 6.0.0"
simplifile = ">= 2.2.1 and < 3.0.0"
argv = ">= 1.0.2 and < 2.0.0"
filepath = ">= 1.1.2 and < 2.0.0"
glexer = ">= 2.2.1 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
gleescript = ">= 1.5.1 and < 2.0.0"
birdie = ">= 1.3.1 and < 2.0.0"
